### PR TITLE
Update to prismarine-item 1.12.1

### PR DESCRIPTION
**Pull request by stefalce**
Use version instead of protocol id num.

### CODE REVIEW

**Comment by IceTank** [comment]
you should just use bot instead off falling back to pclient. If bot is not ready generating packets should not be viable in the first place

**Comment by stefalce** [comment]
You need to use pclient or you'd be assuming to always generate packets for a client on the same version of the server. My change keeps same functionality you had before, it just avoids sending a number to node-minecraft-data (which is not supported).

**Comment by IceTank** [comment]
Well mcproxy only works for one version at the moment anyway so you could even just put '1.12.2' in it and hard code it. If multi version support is added at some point we should probably provide the version we want packets generated for. Then we can use that as the version source.

**Comment by stefalce** [comment]
I think this is why you already had that in place I don't know for what version it works, maybe it's just to support all 1.12.X, I can't check if they got some protocol differences.

**Comment by rob9315** [comment]
there is no difference in terms of item for 1.12 vs 1.12.2. it is supposed to mirror the connected client's version

**Comment by rob9315** [comment]
was fixed in #19

**Pull request closed without merging**
